name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  chromium_linux:
    name: "Chromium Linux"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - name: install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libgbm-dev xvfb
    - run: npm install
    - run: xvfb-run --auto-servernum npm run ccoverage

  chromium_mac:
    name: "Chromium Mac"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - run: npm install
    - run: npm run ctest

  chromium_win:
    name: "Chromium Win"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - run: npm install
    - run: npm run ctest

  webkit_linux:
    name: "WebKit Linux"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - name: install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-2.1-6 libnotify4 libxslt1.1
        sudo apt-get install xvfb
    - run: npm install
    - run: xvfb-run --auto-servernum npm run wcoverage

  webkit_mac:
    name: "WebKit Mac"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - run: npm install
    - run: npm run wtest

  webkit_win:
    name: "WebKit Win"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - run: npm install
    - run: npm run wtest -- --verbose
      env:
        DEBUG: "*launch*"

  firefox_linux:
    name: "Firefox Linux"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - name: install required packages
      run: |
        sudo apt-get update
        sudo apt-get install xvfb
    - run: npm install
    - run: xvfb-run --auto-servernum npm run fcoverage

  firefox_mac:
    name: "Firefox Mac"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - run: npm install
    - run: npm run ftest

  firefox_win:
    name: "Firefox Win"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 10.15
    - run: npm install
    - run: npm run ftest
